name: nop_gen
description: route generator for flutter_nop plugin
version: 0.2.3
repository: https://github.com/sersr/nop_gen

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  source_gen: ">=1.2.2 <2.0.0"
  analyzer: ">=5.1.0 <6.0.0"
  build: ">=2.3.0 <3.0.0"
  nop_annotations: ">=0.2.0 <0.3.0"

dev_dependencies:
  test: ^1.16.4
  build_runner: any
  lints: ^2.0.0
