name: nop_db_gen
description: A new Flutter package project.
version: 0.0.1
homepage: none
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  source_gen: ^1.0.0
  nop_annotations:
    git: https://github.com/sersr/nop_annotations.git
  nop_db:
    git: https://github.com/sersr/nop_db.git
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
