name: nop_db_gen
description: nop_db code generation.
version: 0.1.2
homepage: none
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  source_gen: any
  nop_annotations:
    git:
      url: https://github.com/sersr/nop_annotations.git
  nop_db:
    git:
      url: https://github.com/sersr/nop_db.git
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  flutter_lints: any
