name: nop_db_gen
description: nop_db code generation.
version: 0.1.0
homepage: none
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  source_gen: any
  nop_annotations:
    path: ../nop_annotations
  nop_db:
    path: ../nop_db
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  flutter_lints: any
