name: nop_db_gen
description: nop_db code generation.
version: 0.0.2+4
homepage: none
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  source_gen: any
  # nop_annotations:
  #   git: 
  #     url: https://github.com/sersr/nop_annotations
  #     ref: master
  nop_annotations:
    path: ../nop_annotations
  # nop_db:
  #   git: 
  #     url: https://github.com/sersr/nop_db
  #     ref: master
  nop_db:
    path: ../nop_db
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  flutter_lints: ^1.0.0
