name: nop_gen
description: nop 代码生成
version: 0.1.3
repository: https://github.com/sersr/nop_gen

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  source_gen: ^1.2.2
  analyzer: ^4.1.0
  build: ^2.3.0
  nop_annotations: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  flutter_lints: any
